# use PyPI trusted publishing, as described here:
# https://blog.trailofbits.com/2023/05/23/trusted-publishing-a-new-benchmark-for-packaging-security/
name: publish to pypi

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v5
      - name: install
        run: uv sync --group build
      - name: build package
        run: uv run python -m build
      - name: upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
      - name: publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          print-hash: true
