name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests in ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.9
          - python: 3.13
    steps:
    - name: Checkout python-evtx with submodules
      uses: actions/checkout@v2
      with:
        submodules: true

    - uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.2"
        python-version: ${{ matrix.python-version }}

    - name: install
      run: uv sync --all-extras

    - uses: extractions/setup-just@v2
      with:
        just-version: 1.5.0

    - name: lint
      run: just lint


    - name: test
      run: just test
